import {itinerary,sumBudget,total,money,mapURL,googleURL,weatherURL,exactWeather,weatherText,clothing,validatePlan,safeLoad} from './core.mjs';
const $=s=>document.querySelector(s), main=$('#main');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,text)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(text)} ↗</a>`;
const KEY='national-day-2026-v2';
let storage=null,saveOK=true;
try{storage=window.localStorage;storage.setItem(`${KEY}-probe`,'1');storage.removeItem(`${KEY}-probe`);}catch{saveOK=false;}
const saved=safeLoad(storage,KEY,{});
let checked=saved.checked&&typeof saved.checked==='object'?saved.checked:{};
let notes=typeof saved.notes==='string'?saved.notes:'';
if(!notes)try{notes=storage?.getItem('roadbook-2026-note')||'';}catch{}
const params=new URLSearchParams(location.search);
let state={route:params.get('route')||saved.route||'anhui',date:params.get('dates')||saved.date||'2-7',day:Math.max(0,Number(params.get('day')||saved.day||0))};
let data,current,map,observer,weatherGeneration=0,routeCache,weatherCache=new Map();
const sleepLabel=s=>s.type==='hotel'?'酒店休整':s.type==='car'?'车宿 · 许可待确认':'返回家中';
function announce(message){$('#live-status').textContent=message;}
function storageMessage(){return saveOK?'自动保存于当前浏览器 localStorage，仅此设备、此浏览器可用；不上传 GitHub，不支持跨设备同步。清除网站数据或隐私模式结束可能丢失。':'当前浏览器无法持久保存：勾选与备注仅本次页面临时保留，刷新可能丢失。请截图备份。';}
function persist(){try{if(!storage)throw new Error('No storage');storage.setItem(KEY,JSON.stringify({...state,checked,notes}));saveOK=true;}catch{saveOK=false;}document.querySelectorAll('.storage-note').forEach(n=>n.textContent=storageMessage());}
function syncURL(){const u=new URL(location.href);u.searchParams.set('route',state.route);u.searchParams.set('dates',state.date);u.searchParams.set('day',state.day);history.replaceState(null,'',u);}
async function fetchJSON(url,timeout=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,cache:'no-cache'});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json();}finally{clearTimeout(t);}}
const heading=(n,title,sub='')=>`<div><span class="section-no">${n} / YOUR JOURNEY</span><h2>${title}</h2>${sub?`<p class="meta">${sub}</p>`:''}</div>`;
function budgetTable(b){return `<table class="budget-table"><caption class="sr-only">两人每日或全程预算估算</caption><tbody>${['住宿 · 1间房 / 1辆车','交通 · 1辆车，充电及停车','门票 · 两人预留，非报价','餐饮 · 两人'].map((t,i)=>`<tr><th scope="row">${t}</th><td>${money(b.slice(i*2,i*2+2))}</td></tr>`).join('')}</tbody></table><p class="budget-total">合计 ${money(total(b))}</p>`;}
function normalize(){current=itinerary(data,state.route,state.date);state.route=current.route.id;state.date=current.slot.id;state.day=Number.isFinite(state.day)?Math.min(current.days.length-1,Math.floor(state.day)):0;state.day=Math.max(0,state.day);}
function render(){
 normalize();if(map){map.remove();map=null;}if(observer)observer.disconnect();
 const {route,slot,days}=current,budget=sumBudget(days),grand=total(budget),nights=days.slice(0,-1),moves=nights.slice(1).filter((d,i)=>d.city!==nights[i].city).length;
 main.innerHTML=`<section class="hero" aria-labelledby="hero-title"><div class="hero-copy"><p class="eyebrow">2026 · NATIONAL DAY ROAD TRIP</p><h1 id="hero-title">${route.id==='anhui'?'在徽州，<br>慢慢过几天。':'往江南，<br>再走远一点。'}</h1><p class="lede">${esc(route.intro)}</p><div class="chips"><span class="chip">${esc(slot.label)}</span><span class="chip">2 人 · 1 位司机</span><span class="chip">纯电实际续航 450 km</span></div></div><figure class="hero-media"><img id="destination-photo" src="${route.image}" alt="${route.imageAlt}" fetchpriority="high"><div class="image-fallback">目的地照片暂未加载<br><small>不影响查看行程与清单</small></div><figcaption>${esc(route.imageCredit)} · 历史实景，非本次实时画面<br>${link(route.imageSource,'Zhangzhugang / Wikimedia Commons')} · ${link('https://creativecommons.org/licenses/by-sa/4.0/','CC BY-SA 4.0')} · 显示裁切</figcaption></figure></section>
 <div class="controls"><div><span class="control-label">选择山水的方向</span><div class="route-toggle" role="group" aria-label="目的地路线">${data.routes.map(r=>`<button data-route="${r.id}" aria-pressed="${r.id===route.id}">${r.name}路线</button>`).join('')}</div></div><div class="date-control"><label class="control-label" for="date-select">出行日期 · 2026 年</label><select id="date-select">${data.dates.map(d=>`<option value="${d.id}" ${d.id===slot.id?'selected':''}>${d.label}</option>`).join('')}</select></div></div>
 <section id="overview" class="section" style="margin-top:0"><div class="section-heading">${heading('01','一眼看懂这趟旅程',`${route.name} · ${route.tag}`)}</div><div class="stats"><div class="stat"><strong>${days.length} 天 ${days.length-1} 晚</strong><span>车宿 ${days.length-2} 晚 + 酒店 1 晚</span></div><div class="stat"><strong>${moves} 次换区</strong><span>相邻过夜城市变化，不含返家</span></div><div class="stat"><strong>5–8 km 内</strong><span>每日步行上限 · 午休 90 分钟</span></div><div class="stat"><strong>${money(grand)}</strong><span>两人全程估算 · 另留机动金</span></div></div>
 <p class="notice">${esc(route.tradeoff)}<br>以每天约 4 h 实驾为目标；国庆拥堵可能超出。早上通常 6–7 点出发，酒店休整后安排一天 8–9 点出发。</p><div class="overview-grid"><div class="panel"><h3>每天去哪里</h3><ol class="route-list">${days.map((d,i)=>`<li><button class="route-entry" data-open-day="${i}"><span class="route-num">0${i+1}</span><span><strong>${esc(d.title)}</strong><small>${d.date.slice(5).replace('-','/')} · ${esc(d.stay.area)} · ${sleepLabel(d.stay)}</small></span></button></li>`).join('')}</ol></div><div class="panel"><h3>路线地图</h3><div id="map" class="map-wrap" aria-label="路线地图，近似城市与景点位置"></div><div id="map-state" class="map-state" role="status">正在加载底图…</div><p class="map-meta">实线为已缓存道路，虚线仅为地点连接示意；无实时路况。标记是区域参考点，不是精确入口或车宿许可。深澳、茶园、仙都等市内支线请用下方每日地图入口导航。</p><div class="links">${link(googleURL(route.id==='anhui'?'安徽省黄山市':'浙江省桐庐县'),'Google 地图查看区域')}</div></div></div>
 <details class="panel sources"><summary>全程预算怎么算？查看明细与假设</summary>${budgetTable(budget)}<p class="meta">以上均为估算：住宿按 1 间房或 1 辆车 / 晚，交通按 1 辆车，门票与餐饮按两人。门票仅预留，未报价、未购票。酒店目标约 ¥300，暂按 ¥300–500 / 房预留，国庆实际价待核实；停车车宿 ¥0–80 不代表已获免费许可。</p><p class="meta">另留 ¥400–600 机动金，总准备约 ${money([grand[0]+400,grand[1]+600])}。不含购物、装备购置、车辆折旧、第二晚酒店及临时付费体验。高速按符合免费政策的小客车估算，非符合车型另计。政策来源见行前检查。</p></details></section>
 <section id="daily" class="section"><div class="section-heading">${heading('02','一天只抓住一两件事','其余安排可以删减，休息不挤掉。')}</div><div id="day-tabs" class="day-tabs" role="group" aria-label="选择每日行程"></div><div id="day-content"></div></section>
 <section id="weather" class="section"><div class="section-heading">${heading('03','看天气，再决定穿什么','按旅行日期和经过城市匹配，不以今天代替出行日。')}<button id="refresh-weather">刷新天气</button></div><p class="notice blue">来源：${link('https://open-meteo.com/en/docs','Open-Meteo 数值预报')}（非中国气象部门官方预警）。最多尝试获取未来 16 天；第 8–16 天仅作趋势参考。返回数据未覆盖、日期已过或网络失败时显示“待更新”。不使用历史气候冒充当日预报。</p><div id="weather-grid" class="weather-grid"></div></section>
 <section id="packing" class="section"><div class="section-heading">${heading('04','轻装上路，一起打勾','个人物品分开勾选，共用品只带一份。可选项不计入必备进度。')}</div><div class="panel"><div class="pack-intro"><div><h3>两个人的行李清单</h3><p class="meta">先按通用准备装包，出发前再根据实况增减衣物与被褥。</p></div><span id="pack-count" class="progress-count"></span></div><div class="progress" aria-hidden="true"><span id="pack-progress"></span></div><p class="storage-note">${storageMessage()}</p><div id="packing-grid" class="packing-grid"></div></div></section>
 <section id="checks" class="section"><div class="section-heading">${heading('05','出发前，最后确认一下','未勾选并不代表未准备；勾选也不代替官方确认或实际预订。')}</div><div class="panel"><div class="checklist">${data.checks.map(([id,label])=>checkbox(`check-${id}`,label)).join('')}</div><p class="notice warn">车宿先试睡：按车辆手册确认驻车空调可持续运行。实际续航 450 km 不是应全部用完的里程；建议电量降至约 30% 时主动找充电，夜宿前额外留空调余量（经验缓冲，非车型耗电保证）。充满/充够后离开充电车位，不占位睡整夜。</p><label for="trip-notes"><h3>同行备忘</h3></label><textarea id="trip-notes" placeholder="例如：酒店订单、确认允许过夜的停车场、备选充电站。请勿填密码、证件号码等敏感信息。">${esc(notes)}</textarea><p class="storage-note">${storageMessage()}</p></div>
 <div class="status-grid section"><div class="panel"><h3>已确定 · 需求</h3><p>常州往返；两人、一位司机；实际续航 450 km；三种日期窗口；每日午休；少量爬坡、避开高处；1 晚酒店起步。</p><p>这是已确认偏好，不表示已订车位、酒店或门票。</p></div><div class="panel"><h3>待核实 · 临时信息</h3><p>2026 国庆景区开放、精确入口、交通管控、预约放票时间、实时票价、天气预警、商家营业与逐夜车宿许可。</p></div><div class="panel"><h3>待预约 · 按所选路线</h3><p>可取消酒店；桃花潭 / 呈坎或仙都的入园与接驳；需要预约的体验。先核实规则，再下单，不预设免费与免预约。</p></div></div>
 <details class="panel sources"><summary>事实来源与实现边界 · 查询日期 ${data.checked}</summary><ul>${data.sources.map(([title,url,note])=>`<li>${link(url,title)}<br>${esc(note)}<br><small>查询：${data.checked}；旧公告不作为今年国庆政策。</small></li>`).join('')}</ul><p class="meta">本页可切换路线/日期、打开外部地图、获取可用天气并本地勾选。没有账号、跨设备同步、自动订票、实时路况/充电排队或离线完整地图；不会自动推送提醒。网页照片为有署名历史实景，不表示当前开放状态。旧版 PDF 保留在仓库中，但未同步本版，不作当前攻略使用。</p></details></section>`;
 const credit=document.querySelector('.hero-media figcaption a');credit.textContent=`${route.imageAuthor} / Wikimedia Commons ↗`;
 const photo=$('#destination-photo');photo.addEventListener('error',()=>photo.parentElement.classList.add('failed'));if(photo.complete&&!photo.naturalWidth)photo.parentElement.classList.add('failed');
 renderDay();renderPacking();initMap();renderWeather();loadWeather();observeSections();syncURL();persist();
}
function dailyMapPlaces(d){const names=d.path.map(k=>data.anchors[k][0]);if(d.timeline.some(t=>t.place.includes('深澳')))names.push('浙江省杭州市桐庐县江南镇深澳古村');if(d.timeline.some(t=>t.place.includes('大木山')))names.push('浙江省丽水市松阳县大木山骑行茶园');if(d.timeline.some(t=>t.place.includes('仙都')))names.push('浙江省丽水市缙云县仙都景区鼎湖峰');if(d.timeline.some(t=>t.place.includes('朱潭山')))names.push('浙江省丽水市缙云县仙都朱潭山');return [...new Set(names)];}
function renderDay(){const {days}=current,d=days[state.day];$('#day-tabs').innerHTML=days.map((x,i)=>`<button class="day-tab" data-day="${i}" aria-pressed="${i===state.day}" aria-controls="day-content">第 ${i+1} 天 <small>${x.date.slice(5).replace('-','/')} · ${data.cities[x.city][0]}</small></button>`).join('');const labels={core:'核心安排',optional:'可删减',rest:'休息 / 缓冲',drive:'交通 · 耗时估算',food:'用餐'};$('#day-content').innerHTML=`<div class="day-layout"><article class="panel"><header class="day-intro"><p class="eyebrow">DAY ${state.day+1} / ${d.date}</p><h3>${esc(d.title)}</h3><div class="chips"><span class="chip">步行 ${d.walk}</span><span class="chip">实驾估算 ${d.drive}</span></div><p class="meta" style="margin-top:12px">强度：${parseInt(d.walk)>=5?'轻至中等，注意累计步数':'轻量，以休息为主'}。下列时间是计划，不是营业承诺；景区段须匹配预约时段。</p></header><ol class="timeline">${d.timeline.map(e=>`<li class="${e.kind}"><time>${e.time}</time><div class="event"><span class="kind ${e.kind}">${labels[e.kind]}</span><strong>${esc(e.place)}</strong><p>${esc(e.note)}</p></div></li>`).join('')}</ol></article><aside class="side-stack"><section class="panel"><h3>今晚住哪里</h3><p><strong>${esc(d.stay.area)}</strong> · ${sleepLabel(d.stay)}</p><p>${esc(d.stay.reason)}</p></section><section class="panel"><h3>吃什么 · 在哪里找</h3><p>${esc(d.food)}</p><p class="meta">只推荐品类与区域；具体餐馆营业、价格、座位另行核实。</p></section><section class="panel"><h3>拍照与预约</h3><p>${esc(d.photo)}</p><p><strong>预约提醒：</strong>${esc(d.booking)}</p></section><section class="panel"><h3>当天预算 · 两人估算</h3>${budgetTable(d.budget)}<p class="meta">门票为预算预留，非已核实票价。交通不含车辆折旧。</p></section><section class="panel"><h3>Plan B · 不硬赶</h3><p>${esc(d.planB)}</p><p class="meta">出发前改：确认退改规则、预约时段和备选酒店；遇关闭/预警取消户外活动，不绕封闭路线。</p></section><section class="panel"><h3>打开对应地点地图</h3><div class="links">${dailyMapPlaces(d).map(n=>link(mapURL(n),n.replace(/安徽省|浙江省|黄山市|杭州市|丽水市/g,''))).join('')}</div><p class="meta">以上打开高德地点搜索，出发前选定实际入口。不要把地图区域点当作停车入口。</p>${link(googleURL(dailyMapPlaces(d).at(-1)),'Google 地图备选')}</section></aside></div>`;}
function checkbox(id,label,optional=false){return `<label class="check-label"><input type="checkbox" data-check="${id}" ${optional?'data-optional="true"':''} ${checked[id]===true?'checked':''}><span>${esc(label)}</span></label>`;}
function renderPacking(){const cats=[...new Set(data.packing.map(p=>p[0]))];$('#packing-grid').innerHTML=cats.map(cat=>`<section class="packing-group"><h3>${cat}</h3>${data.packing.filter(p=>p[0]===cat).map(([,owner,id,label])=>`<div class="pack-item"><div class="pack-title"><span class="owner ${owner}">${owner==='personal'?'每人自带':owner==='shared'?'同行共用':'可选'}</span><span>${esc(label)}</span></div><div class="check-row">${owner==='personal'?checkbox(`pack-${id}-1`,'同行者 1')+checkbox(`pack-${id}-2`,'同行者 2'):checkbox(`pack-${id}`,'已准备',owner==='optional')}</div></div>`).join('')}</section>`).join('');updateProgress();}
function updateProgress(){const boxes=[...document.querySelectorAll('#packing input:not([data-optional])')],done=boxes.filter(b=>b.checked).length;$('#pack-count').textContent=`${done} / ${boxes.length}`;$('#pack-progress').style.width=`${done/boxes.length*100}%`;}
async function initMap(){const mount=$('#map'),status=$('#map-state');if(!window.L){status.textContent='地图组件加载失败；请使用每日地点导航链接。';return;}const localMap=map=L.map(mount,{scrollWheelZoom:false});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>{if(map===localMap)status.textContent='部分底图加载失败；路线标记仍可见，请用每日地图入口导航。';}).on('load',()=>{if(map===localMap&&!status.textContent.includes('失败'))status.textContent='区域参考图 · 无实时路况';}).addTo(localMap);const keys=[...new Set(current.days.flatMap(d=>d.path))];const points=keys.map(k=>data.anchors[k].slice(1));keys.forEach((k,i)=>L.marker(data.anchors[k].slice(1),{icon:L.divIcon({className:'leaflet-marker-custom',html:String(i+1),iconSize:[28,28],iconAnchor:[14,14]})}).bindTooltip(data.anchors[k][0]).addTo(localMap));localMap.fitBounds(points,{padding:[26,26]});setTimeout(()=>{if(map===localMap)localMap.invalidateSize();},50);const paths=current.days.map(d=>d.path);try{routeCache=routeCache||await fetchJSON('data/routes.json');}catch{routeCache=null;status.textContent='道路数据加载失败；虚线仅示意，使用外部地图导航。';}if(map!==localMap)return;const drawn=new Set();for(const path of paths)for(let i=1;i<path.length;i++){const a=path[i-1],b=path[i],id=[a,b].sort().join('--');if(a===b||drawn.has(id))continue;drawn.add(id);const segment=routeCache?.segments?.[`${a}--${b}`]||routeCache?.segments?.[`${b}--${a}`];const geometry=segment?.geometry?.coordinates;if(geometry)L.polyline(geometry.map(c=>[c[1],c[0]]),{color:'#376447',weight:3,opacity:.85}).addTo(localMap);else L.polyline([data.anchors[a].slice(1),data.anchors[b].slice(1)],{color:'#477d97',weight:3,dashArray:'6 7'}).addTo(localMap);}}
const weatherCityKey={taohuatan:'jingxian',lucun:'yixian',xixinan:'huizhou',chengkan:'huizhou',yansi:'huizhou'};
function citiesFor(d){return [...new Set(d.path.map(k=>weatherCityKey[k]||k).filter(k=>data.cities[k]))];}
function weatherBody(cityKey,date){const city=data.cities[cityKey],entry=weatherCache.get(cityKey),w=exactWeather(entry?.payload,date),today=new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date()),delta=(Date.parse(date)-Date.parse(today))/86400000;const usable=w&&delta>=0?w:null;return `<div class="city-weather"><h3>${esc(city[0])}</h3>${usable?`<div class="weather-temp">${usable.min}–${usable.max}°C</div><p>${weatherText(usable.code)} · 降水概率 ${Number.isFinite(usable.rain)?usable.rain+'%':'未提供'}</p><p class="weather-status">${delta>=7?'中期趋势 · 不宜据此锁定户外活动':'可用日期预报 · 仍须临行复查'}</p>`:`<div class="weather-temp">待更新</div><p class="weather-status">${!entry?'正在查询对应日期…':entry.error?'天气加载失败，可重试或查看官方渠道。':'接口未覆盖此旅行日期 / 日期已过，不生成每日温度。'}</p>`}<p>${clothing(usable)}</p><p class="meta">${entry?.retrievedAt?'获取时间：'+esc(entry.retrievedAt)+'（北京时间）<br>模型发布时间：接口未提供。':'尚无成功获取记录。'}</p>${link(`https://www.weather.com.cn/weather15d/${city[3]}.shtml`,'中国天气网参考')}</div>`;}
function renderWeather(){if(!current||!$('#weather-grid'))return;$('#weather-grid').innerHTML=current.days.map((d,i)=>`<article class="panel weather-card"><p class="eyebrow">DAY ${i+1} · ${d.date}</p>${citiesFor(d).map(k=>weatherBody(k,d.date)).join('<hr>')}<p class="meta">活动适配：${d.walk.includes('坡')||d.walk.includes('石板')?'湿滑石板和缓坡谨慎慢走；':'平地步行也穿防滑鞋；'}${d.stay.type==='car'?'车宿被褥按夜间最低温另留保暖余量。':'酒店/家中休息，次晨出门再确认降雨。'}</p></article>`).join('');}
async function loadWeather(force=false){const generation=++weatherGeneration,button=$('#refresh-weather');button.disabled=true;button.textContent='正在查询…';const keys=[...new Set(current.days.flatMap(citiesFor))];await Promise.all(keys.map(async key=>{const old=weatherCache.get(key);if(!force&&old&&!old.error&&Date.now()-old.at<600000)return;try{const payload=await fetchJSON(weatherURL(data.cities[key]),8000);if(!Array.isArray(payload?.daily?.time))throw new Error('Invalid weather response');weatherCache.set(key,{payload,at:Date.now(),retrievedAt:new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',dateStyle:'short',timeStyle:'short'}).format(new Date())});}catch{weatherCache.set(key,{error:true,at:Date.now()});}if(generation===weatherGeneration)renderWeather();}));if(generation!==weatherGeneration)return;renderWeather();button.disabled=false;button.textContent='刷新天气';}
function observeSections(){observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio);if(visible[0])document.querySelectorAll('.main-nav a').forEach(a=>{const yes=a.hash===`#${visible[0].target.id}`;a.classList.toggle('active',yes);if(yes)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-10% 0px -45% 0px',threshold:0});['overview','daily','weather','packing','checks'].forEach(id=>observer.observe(document.getElementById(id)));}
main.addEventListener('click',e=>{const route=e.target.closest('[data-route]');if(route){state.route=route.dataset.route;state.day=0;render();document.querySelector(`[data-route="${state.route}"]`).focus({preventScroll:true});announce('已切换路线，日期与预算已更新');return;}const day=e.target.closest('[data-day],[data-open-day]');if(day){state.day=Number(day.dataset.day??day.dataset.openDay);renderDay();persist();syncURL();if(day.hasAttribute('data-open-day')){$('#daily').scrollIntoView({behavior:'auto'});history.replaceState(null,'',location.pathname+location.search+'#daily');}document.querySelector(`[data-day="${state.day}"]`).focus({preventScroll:true});announce('已打开第 '+(state.day+1)+' 天');return;}if(e.target.closest('#refresh-weather'))loadWeather(true);if(e.target.closest('#retry-load'))boot();});
main.addEventListener('change',e=>{if(e.target.id==='date-select'){state.date=e.target.value;state.day=0;render();$('#date-select').focus({preventScroll:true});announce('出行日期已更新');}if(e.target.matches('[data-check]')){checked[e.target.dataset.check]=e.target.checked;persist();updateProgress();announce(saveOK?'已保存到本浏览器':'仅临时保存，请截图备份');}});
main.addEventListener('input',e=>{if(e.target.id==='trip-notes'){notes=e.target.value;persist();}});
window.addEventListener('popstate',()=>{if(!data)return;const p=new URLSearchParams(location.search);state={route:p.get('route')||'anhui',date:p.get('dates')||'2-7',day:Number(p.get('day')||0)};render();});
async function boot(){main.innerHTML='<div class="loading" role="status">正在整理你的山水路书…</div>';try{data=validatePlan(await fetchJSON('data/plan.json'));render();if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView());}catch{main.innerHTML='<div class="error-state" role="alert"><h1>路书暂未加载</h1><p>可能是网络中断、网页更新中或数据格式异常。你的本地清单不会被清空。</p><button class="primary" id="retry-load">重新加载行程</button><p class="meta">本页需要通过网站或本地 HTTP 服务打开；直接双击 HTML 文件可能无法读取数据。</p></div>';}}
boot();
