export const dateAt=(start,offset)=>new Date(Date.parse(`${start}T00:00:00Z`)+offset*86400000).toISOString().slice(0,10);
export function itinerary(data,routeId,dateId){const route=data.routes.find(r=>r.id===routeId)||data.routes[0];const slot=data.dates.find(d=>d.id===dateId)||data.dates[0];return {route,slot,days:route.variants[slot.length].map((d,i)=>({...d,date:dateAt(slot.start,i)}))};}
export const sumBudget=days=>days.reduce((acc,d)=>acc.map((n,i)=>n+d.budget[i]),Array(8).fill(0));
export const total=b=>[b[0]+b[2]+b[4]+b[6],b[1]+b[3]+b[5]+b[7]];
export const money=b=>`¥${b[0].toLocaleString('zh-CN')}–${b[1].toLocaleString('zh-CN')}`;
export const mapURL=name=>`https://uri.amap.com/search?keyword=${encodeURIComponent(name)}&callnative=1`;
export const googleURL=name=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;
export const weatherURL=c=>`https://api.open-meteo.com/v1/forecast?latitude=${c[1]}&longitude=${c[2]}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max&timezone=Asia%2FShanghai&forecast_days=16`;
export function exactWeather(payload,date){const d=payload?.daily;if(!Array.isArray(d?.time))return null;const i=d.time.indexOf(date);if(i<0)return null;const out={date,min:d.temperature_2m_min?.[i],max:d.temperature_2m_max?.[i],code:d.weather_code?.[i],rain:d.precipitation_probability_max?.[i],wind:d.wind_speed_10m_max?.[i]};return [out.min,out.max,out.code].every(Number.isFinite)&&out.min<=out.max?out:null;}
export function weatherText(c){if(c===0)return '晴';if(c<=3)return '晴间多云 / 阴';if(c<=48)return '雾';if(c<=67)return '雨';if(c<=77)return '雪';if(c<=82)return '阵雨';if(c<=86)return '阵雪';if(c>=95)return '雷暴';return '天气类型待确认';}
export function clothing(w){if(!w)return '仅通用准备：短袖/长袖叠穿，薄保暖层与带帽防雨外套；长裤、防滑步行鞋、雨伞。车宿被褥等临近预报再定厚度。';const p=[];p.push(w.min<15?'早晚加抓绒/卫衣与外套，车宿加强保暖':'早晚长袖或薄外套，可分层增减');p.push(w.max>=25?'白天备透气短袖，遮阳帽、防晒与饮水':'白天以长袖/薄层叠穿，活动后及时增减');p.push('防滑闭口步行鞋，避免新鞋');p.push((Number.isFinite(w.rain)&&w.rain>=40)||w.code>=51?'随身雨衣/防雨外套与防水袋，备用干袜；石板路、溪边减量':'雨伞轻量随身备用');if(w.code>=95||w.wind>=40)p.push('关注预警，暂停临水、林地与观景台活动');return p.join('；')+'。';}
export function validatePlan(d){if(!d||!Array.isArray(d.routes)||d.routes.length!==2||!Array.isArray(d.dates)||!d.cities||!d.anchors)throw new Error('行程数据格式不完整');for(const r of d.routes)for(const len of [5,6]){const days=r.variants?.[len];if(!Array.isArray(days)||days.length!==len)throw new Error('行程天数不匹配');for(const day of days){if(!day.title||!d.cities[day.city]||!Array.isArray(day.timeline)||!day.timeline.length||!Array.isArray(day.budget)||day.budget.length!==8||!day.budget.every(Number.isFinite))throw new Error('每日内容不完整');}}return d;}
export function safeLoad(storage,key,fallback){try{const v=JSON.parse(storage.getItem(key));return v&&typeof v==='object'&&!Array.isArray(v)?v:fallback;}catch{return fallback;}}
