import {mkdir,copyFile,cp,access,writeFile} from 'node:fs/promises';
import {plan} from '../data/plan.mjs';
import {validatePlan} from '../core.mjs';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const files=['index.html','app.js','core.mjs','itinerary-map.mjs','style.css','favicon.svg','LICENSE','NOTICE.md','README.md','site-config.json','.nojekyll'];
validatePlan(plan);
await writeFile(path.join(root,'data','plan.json'),JSON.stringify(plan,null,2)+'\n','utf8');
for(const f of files)await access(path.join(root,f));
await mkdir(path.join(root,'dist'),{recursive:true});
for(const f of files)await copyFile(path.join(root,f),path.join(root,'dist',f));
for(const f of ['data','vendor','assets'])await cp(path.join(root,f),path.join(root,'dist',f),{recursive:true});
console.log('Static site built in dist/. No secrets or server components included.');
